version: '3'
services:
  dynamodb:
    image: amazon/dynamodb-local
    container_name: 'dynamodb'
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - /dev/shm:/dev/shm

  python:
    depends_on:
      - 'dynamodb'
    build: './python'
    container_name: 'python'
    command: 'tail -f /dev/null'
    working_dir: '/root/script/'
    volumes:
      - ./script/:/root/script/
    environment:
      - 'TZ=Asia/Tokyo'
